# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vwidget',
                'doc_host': 'https://civvic.github.io',
                'git_url': 'https://github.com/civvic/vwidget',
                'lib_path': 'vwidget'},
  'syms': {'vwidget.core': {'vwidget.core.foo': ('core.html#foo', 'vwidget/core.py')}}}
